In [ ]:
import numpy as np
import pandas as pd
import torch
from torch.utils.data import Dataset,DataLoader

# Types of torch.nn Layers + torch.optim Optimization function + torch.nn Loss function

# PyTorch Tensors

In [ ]:
import torch
import numpy as np

np_array = np.array([[1,2],[3,4]])
torch_array = torch.from_numpy(np_array)
print(f"torch_array : {torch_array}")
torch_ones = torch.ones_like(torch_array,dtype=torch.float)
print(f"torch_ones : {torch_ones}")
shape = (2,3)
torch_rand = torch.rand(shape)
print(f"torch_rand : {torch_rand}")
torch_arange = torch.arange(start=1,end=11,step=2)
print(f"torch_arange : ",{torch_arange})

torch_array : tensor([[1, 2],
        [3, 4]])
torch_ones : tensor([[1., 1.],
        [1., 1.]])
torch_rand : tensor([[0.1420, 0.1922, 0.5319],
        [0.3657, 0.0430, 0.8208]])
torch_arange :  {tensor([1, 3, 5, 7, 9])}


# Tensor Indexing

In [ ]:
x = torch.reshape(torch.arange(1,13,1,dtype=torch.float),(4,3))
print(f"First row: {x[0]}")
print(f"First column: {x[:, 0]}")
print(f"Last column: {x[..., -1]}")
x[:,1] = 0
print(x)
tensor1 = torch.randn(10, 3, 4)
print(tensor1[:,0,0].shape,tensor1[0,:,0].shape,tensor1[0,0,:].shape)
print(tensor1)
tensor2 = torch.randn(4)
print(tensor2)

First row: tensor([1., 2., 3.])
First column: tensor([ 1.,  4.,  7., 10.])
Last column: tensor([ 3.,  6.,  9., 12.])
tensor([[ 1.,  0.,  3.],
        [ 4.,  0.,  6.],
        [ 7.,  0.,  9.],
        [10.,  0., 12.]])
torch.Size([10]) torch.Size([3]) torch.Size([4])
tensor([[[-0.4198, -1.3901, -0.7433,  1.6252],
         [-1.3204,  0.2975, -1.9061,  0.4013],
         [-1.2086, -0.6729,  0.2693, -0.2020]],

        [[-0.2129, -0.5784, -0.1382, -0.1359],
         [-0.1326,  0.9448, -0.8960, -0.1384],
         [-1.1900, -0.6642, -0.3136,  0.3689]],

        [[-0.4662, -1.3043, -1.4399,  0.4012],
         [ 1.5566,  1.7305, -0.0877,  0.4483],
         [-0.0824, -0.9446, -0.5587, -0.3315]],

        [[ 0.2831, -0.3476,  1.2822,  0.4452],
         [ 1.3330, -2.1681,  0.7457,  1.1190],
         [ 0.8063,  0.6081,  0.6591, -0.6953]],

        [[-1.4361,  0.0067,  1.5265,  1.7683],
         [-1.4769,  0.4061,  0.4140, -1.2963],
         [-1.4096, -1.4380,  0.1303,  0.6771]],

        [[-0.8026,

# Tensor Aggreration Operation

In [ ]:
tensor = torch.ones(3, 4)
print(f"tensor : {tensor} \n")
tensor.add_(5)
print("tensor + 5 (inplace using add_ ) ",tensor)
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print("tensor concat : ",t1)


tensor : tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 

tensor + 5 (inplace using add_ )  tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])
tensor concat :  tensor([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.]])


if requires_grad=True then need to detach() before clone()

In [ ]:
a = torch.rand(2, 2, requires_grad=True) # turn on autograd
print("a : ",a)

b = a.clone()
print("b : ",b)

c = a.detach().clone()
print("c : ",c)

try:
    assert b is a
except AssertionError as e:
    print(e)

a = torch.rand(3, 226, 226)
e = torch.rand(1,5)
c = a.clone()

b = a.unsqueeze(0)
d = c.squeeze(0)
f = e.squeeze(0)
print("a.unsqueeze(0) : ",a.shape,b.shape)
print("a.squeeze(0) : ",a.shape,d.shape)
print("e.squeeze(0) : ",e.shape,f.shape)

# Torch Aggregation - groupby

In [ ]:
samples = torch.Tensor([
    [0.1, 0.1],    #-> group / class 1
    [0.2, 0.2],    #-> group / class 2
    [0.4, 0.4],    #-> group / class 2
    [0.0, 0.0]     #-> group / class 0
])

labels = torch.LongTensor([1,2,2,0])

label_size = 3
sample_dim = samples.size(1)
print("sample_dim ",sample_dim)
index = labels.unsqueeze(1)
print("labels.unsqueeze(1) ",index)
index = index.repeat((1, sample_dim))
print("index.repeat((1, sample_dim)) ",index)

res = torch.ones(label_size, sample_dim, dtype=samples.dtype)
print("res ",res)
res.scatter_(0, index, samples, reduce='multiply')

sample_dim  2
labels.unsqueeze(1)  tensor([[1],
        [2],
        [2],
        [0]])
index.repeat((1, sample_dim))  tensor([[1, 1],
        [2, 2],
        [2, 2],
        [0, 0]])
res  tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


tensor([[0.0000, 0.0000],
        [0.1000, 0.1000],
        [0.0800, 0.0800]])

# Matrix Multiplication

    torch.mm - performs a matrix multiplication without broadcasting - (2D tensor) by (2D tensor)
    torch.mul - performs a elementwise multiplication with broadcasting - (Tensor) by (Tensor or Number)
    torch.matmul - matrix product with broadcasting - (Tensor) by (Tensor) with different behaviors depending on the tensor shapes (dot product, matrix product, batched matrix products).
    


    torch.mm - performs a matrix multiplication without broadcasting
It expects two 2D tensors so n×m * m×p = n×p

In [ ]:
x1 = torch.ones(3, 4)
x2 = torch.reshape(torch.arange(1,13,1,dtype=torch.float),(4,3))
print(f"x1 : {x1.shape} ,x2 : {x2.shape}")
y1 = x1 @ x2
y2 = x1.matmul(x2)
assert torch.all(torch.eq(y1,y2)).item()==True
y3 = torch.mm(x1, x2)

# assert torch.all(torch.eq(y3,y2)).item()==True
print("Matrix Multiplication : works with only matching dimensions")
print(f"y1 = x1 @ x2 : shape {y1.shape} : {y1}")
print(f"y2 = x1.matmul(x2) : shape {y2.shape} : {y2}")
print(f"y3 = torch.mm(x1, x2) : shape {y3.shape} : {y3}")

x1 : torch.Size([3, 4]) ,x2 : torch.Size([4, 3])
Matrix Multiplication : works with only matching dimensions
y1 = x1 @ x2 : shape torch.Size([3, 3]) : tensor([[22., 26., 30.],
        [22., 26., 30.],
        [22., 26., 30.]])
y2 = x1.matmul(x2) : shape torch.Size([3, 3]) : tensor([[22., 26., 30.],
        [22., 26., 30.],
        [22., 26., 30.]])
y3 = torch.mm(x1, x2) : shape torch.Size([3, 3]) : tensor([[22., 26., 30.],
        [22., 26., 30.],
        [22., 26., 30.]])


    torch.mul - performs a elementwise multiplication with broadcasting - (Tensor) by (Tensor or Number)

Docs: https://pytorch.org/docs/stable/generated/torch.mul.html

torch.mul does not perform a matrix multiplication. It broadcasts two tensors and performs an elementwise multiplication. So when you uses it with tensors 1x4 * 4x1 it will work similar to:

In [ ]:
a = torch.FloatTensor([[1], [2], [3]])
b = torch.FloatTensor([[1, 10, 100, 1000]])
a, b = torch.broadcast_tensors(a, b)
c = a * b
d = torch.mul(a,b)
print(a)
print(b)
assert torch.all(torch.eq(c,d)).item()==True
print(c)
print(d)


tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])
tensor([[   1.,   10.,  100., 1000.],
        [   1.,   10.,  100., 1000.],
        [   1.,   10.,  100., 1000.]])
tensor([[1.0000e+00, 1.0000e+01, 1.0000e+02, 1.0000e+03],
        [2.0000e+00, 2.0000e+01, 2.0000e+02, 2.0000e+03],
        [3.0000e+00, 3.0000e+01, 3.0000e+02, 3.0000e+03]])
tensor([[1.0000e+00, 1.0000e+01, 1.0000e+02, 1.0000e+03],
        [2.0000e+00, 2.0000e+01, 2.0000e+02, 2.0000e+03],
        [3.0000e+00, 3.0000e+01, 3.0000e+02, 3.0000e+03]])


    torch.matmul

It is better to check out the official documentation https://pytorch.org/docs/stable/generated/torch.matmul.html as it uses different modes depending on the input tensors. It may perform dot product, matrix-matrix product or batched matrix products with broadcasting.

In [ ]:
tensor1 = torch.randn(10, 3, 4)
tensor2 = torch.randn(4)
print(tensor1[:,0,0].shape,tensor1[0,:,0].shape,tensor1[0,0,:].shape)
print(tensor2.shape)
tensor3 = torch.matmul(tensor1,tensor2)
print(tensor3.shape)

# 3x1x3
a = torch.FloatTensor([[[1, 2, 3]], [[3, 4, 5]], [[6, 7, 8]]])
# 3
b = torch.FloatTensor([1, 10, 100])
r1 = torch.matmul(a, b)

r2 = torch.stack((
    torch.matmul(a[0], b),
    torch.matmul(a[1], b),
    torch.matmul(a[2], b),
))
assert torch.allclose(r1, r2)
print(a.shape,b.shape,r1.shape)

torch.Size([10]) torch.Size([3]) torch.Size([4])
torch.Size([4])
torch.Size([10, 3])
torch.Size([3, 1, 3]) torch.Size([3]) torch.Size([3, 1])


In [ ]:
a = torch.ones(4, 3, 2)
b = torch.rand(   3)     # trying to multiply a * b will give a runtime error
c = b.unsqueeze(1)       # change to a 2-dimensional tensor, adding new dim at the end
print("After broadcasting b : ", c.shape)
print("Broadcasing internally : ",torch.mul(a,c).shape)            # broadcasting works again!

output3d = torch.rand(6, 20, 20)
print("output3d : ",output3d.shape)

input1d = output3d.reshape(6 * 20 * 20)
print("input1d : ",input1d.shape)

# can also call it as a method on the torch module:
print("same as above but using torch : ",torch.reshape(output3d, (6 * 20 * 20,)).shape)

# PyTorch Common Math function

In [ ]:
import torch
import math

# common functions
a = torch.rand(2, 4) * 2 - 1
print('Common functions:')
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5))

# trigonometric functions and their inverses
angles = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
sines = torch.sin(angles)
inverses = torch.asin(sines)
print('\nSine and arcsine:')
print(angles)
print(sines)
print(inverses)

# bitwise operations
print('\nBitwise XOR:')
b = torch.tensor([1, 5, 11])
c = torch.tensor([2, 7, 10])
print(torch.bitwise_xor(b, c))

# comparisons:
print('\nBroadcasted, element-wise equality comparison:')
d = torch.tensor([[1., 2.], [3., 4.]])
e = torch.ones(1, 2)  # many comparison ops support broadcasting!
print(torch.eq(d, e)) # returns a tensor of type bool

# reductions:
print('\nReduction ops:')
print(torch.max(d))        # returns a single-element tensor
print(torch.max(d).item()) # extracts the value from the returned tensor
print(torch.mean(d))       # average
print(torch.std(d))        # standard deviation
print(torch.prod(d))       # product of all numbers
print(torch.unique(torch.tensor([1, 2, 1, 2, 1, 2]))) # filter unique elements

# vector and linear algebra operations
v1 = torch.tensor([1., 0., 0.])         # x unit vector
v2 = torch.tensor([0., 1., 0.])         # y unit vector
m1 = torch.rand(2, 2)                   # random matrix
m2 = torch.tensor([[3., 0.], [0., 3.]]) # three times identity matrix

print('\nVectors & Matrices:')
print(torch.cross(v2, v1)) # negative of z unit vector (v1 x v2 == -v2 x v1)
print(m1)
m3 = torch.matmul(m1, m2)
print(m3)                  # 3 times m1
print(torch.svd(m3))       # singular value decomposition

Common functions:
tensor([[0.8587, 0.0493, 0.9242, 0.1247],
        [0.0059, 0.8742, 0.3704, 0.4161]])
tensor([[-0., -0., 1., -0.],
        [1., 1., -0., -0.]])
tensor([[-1., -1.,  0., -1.],
        [ 0.,  0., -1., -1.]])
tensor([[-0.5000, -0.0493,  0.5000, -0.1247],
        [ 0.0059,  0.5000, -0.3704, -0.4161]])

Sine and arcsine:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 0.7854])

Bitwise XOR:
tensor([3, 2, 1])

Broadcasted, element-wise equality comparison:
tensor([[ True, False],
        [False, False]])

Reduction ops:
tensor(4.)
4.0
tensor(2.5000)
tensor(1.2910)
tensor(24.)
tensor([1, 2])

Vectors & Matrices:
tensor([ 0.,  0., -1.])
tensor([[0.1393, 0.9677],
        [0.4260, 0.3730]])
tensor([[0.4178, 2.9031],
        [1.2780, 1.1191]])
torch.return_types.svd(
U=tensor([[-0.8952, -0.4456],
        [-0.4456,  0.8952]]),
S=tensor([3.2382, 1.0014]),
V=tensor([[-0.2914,  0.9566],
        [-0.9566, -0.2914]]))


In [ ]:
import torch
import torch.nn.functional as F

x = torch.arange(1, 11, 1)
print("Original Tensor:", x)

# Ensure the index tensor is of dtype torch.int64
one_hot_encoded = F.one_hot(torch.tensor(x - 1), num_classes=len(x))
print("One-Hot Encoded Tensor:\n", one_hot_encoded.float())

Original Tensor: tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
One-Hot Encoded Tensor:
 tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])


/tmp/ipykernel_32/2904155138.py:8: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  one_hot_encoded = F.one_hot(torch.tensor(x - 1), num_classes=len(x))


In [ ]:
inp = torch.eye(4, 5, requires_grad=True)
out = (inp+1).pow(2).t()
print("inp : \n",inp)
print("out : \n",out)
out.backward(torch.ones_like(out), retain_graph=True)
print(f"First call\n{inp.grad}")
out.backward(torch.ones_like(out), retain_graph=True)
print(f"\nSecond call\n{inp.grad}")
inp.grad.zero_()
out.backward(torch.ones_like(out), retain_graph=True)
print(f"\nCall after zeroing gradients\n{inp.grad}")

inp : 
 tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.]], requires_grad=True)
out : 
 tensor([[4., 1., 1., 1.],
        [1., 4., 1., 1.],
        [1., 1., 4., 1.],
        [1., 1., 1., 4.],
        [1., 1., 1., 1.]], grad_fn=<TBackward0>)
First call
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.]])

Second call
tensor([[8., 4., 4., 4., 4.],
        [4., 8., 4., 4., 4.],
        [4., 4., 8., 4., 4.],
        [4., 4., 4., 8., 4.]])

Call after zeroing gradients
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.]])


In [ ]:
import random
import torch
import math


class DynamicNet(torch.nn.Module):
    def __init__(self):
        """
        In the constructor we instantiate five parameters and assign them as members.
        """
        super().__init__()
        self.a = torch.nn.Parameter(torch.randn(()))
        self.b = torch.nn.Parameter(torch.randn(()))
        self.c = torch.nn.Parameter(torch.randn(()))
        self.d = torch.nn.Parameter(torch.randn(()))
        self.e = torch.nn.Parameter(torch.randn(()))

    def forward(self, x):
        """
        For the forward pass of the model, we randomly choose either 4, 5
        and reuse the e parameter to compute the contribution of these orders.

        Since each forward pass builds a dynamic computation graph, we can use normal
        Python control-flow operators like loops or conditional statements when
        defining the forward pass of the model.

        Here we also see that it is perfectly safe to reuse the same parameter many
        times when defining a computational graph.
        """
        y = self.a + self.b * x + self.c * x ** 2 + self.d * x ** 3
        for exp in range(4, random.randint(4, 6)):
            y = y + self.e * x ** exp
        return y

    def string(self):
        """
        Just like any class in Python, you can also define custom method on PyTorch modules
        """
        return f'y = {self.a.item()} + {self.b.item()} x + {self.c.item()} x^2 + {self.d.item()} x^3 + {self.e.item()} x^4 ? + {self.e.item()} x^5 ?'


# Create Tensors to hold input and outputs.
x = torch.linspace(-math.pi, math.pi, 20)
y = torch.sin(x)

# Construct our model by instantiating the class defined above
model = DynamicNet()

# Construct our loss function and an Optimizer. Training this strange model with
# vanilla stochastic gradient descent is tough, so we use momentum
criterion = torch.nn.MSELoss(reduction='sum')
optimizer = torch.optim.SGD(model.parameters(), lr=1e-8, momentum=0.9)
for t in range(300):
    # Forward pass: Compute predicted y by passing x to the model
    y_pred = model(x)

    # Compute and print loss
    loss = criterion(y_pred, y)
    if t % 20 == 0:
        print(f"epoch :{t+1} -> loss : {loss.item()}")

    # Zero gradients, perform a backward pass, and update the weights.
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

print(f'Result: {model.string()}')

epoch :1 -> loss : 1681.168701171875
epoch :21 -> loss : 1679.867919921875
epoch :41 -> loss : 18472.8984375
epoch :61 -> loss : 1674.7679443359375
epoch :81 -> loss : 2091.922119140625
epoch :101 -> loss : 1560.9306640625
epoch :121 -> loss : 1389.830078125
epoch :141 -> loss : 1360.8319091796875
epoch :161 -> loss : 1669.4376220703125
epoch :181 -> loss : 1257.3314208984375
epoch :201 -> loss : 1205.929443359375
epoch :221 -> loss : 1615.4774169921875
epoch :241 -> loss : 1728.8299560546875
epoch :261 -> loss : 1236.6771240234375
epoch :281 -> loss : 1593.4512939453125
Result: y = 0.14420916140079498 + -0.5590418577194214 x + -1.822824239730835 x^2 + 0.17527174949645996 x^3 + 0.028357358649373055 x^4 ? + 0.028357358649373055 x^5 ?



```python
import torch
from torch import nn

linear_layer = nn.Linear(in_features=10,out_features=5,bias=True)
# conv1d -> text,conv2d -> heightXwidth (image),conv3d - heightXweightXtime (video)
conv_1d = nn.Conv3d(in_channels=3,out_channels=5,kernel_size=3,stride=2,padding=2)




## transformer layer
transformer_model = nn.Transformer()
# single encoder (embedding_dim=768)
encoder_layer = nn.TransformerEncoderLayer(d_model=768,nhead=12)
# stacked encoder
transformer_encoder = nn.TransformerEncoder(encoder_layer=encoder_layer,num_layers=6)
# single decoder layer
decoder_layer = nn.TransformerDecoderLayer(d_model=768,nhead=12)
# stacked decoder layer
transformer_decoder = nn.TransformerDecoder(decoder_layer=decoder_layer,num_layers=6)



# lstm cell
lstm_cell = nn.LSTMCell(input_size=10,hidden_size=5)
# Stack together LSTM cells - 3 stacked cells - similar for GRU
lstm_stack = nn.LSTM(input_size=10,hidden_size=5, num_layers=3)
bidirectional_lstm_stack = nn.LSTM(input_size=10,hidden_size=5,num_layers=3,bidirectional=True)





# activation function - relu,sigmoid,softmax
# ReLU
relu = nn.ReLU()
# Sigmoid
sigmoid = nn.Sigmoid()
# Softmax
softmax = nn.Softmax()



# loss function
# L1Loss
loss_fn = nn.L1Loss() # also known as MAE or mean absolute error
# MSELoss
loss_fn = nn.MSELoss() # also known as MSE or mean squared error
# Binary cross entropy (for binary classification problems)
loss_fn = nn.BCEWithLogitsLoss()
# Cross entropy (for multi-class classification problems)
loss_fn = nn.CrossEntropyLoss()



# optimizer
model = nn.Transformer()
# SGD (stochastic gradient descent)
optimizer = torch.optim.SGD(lr=0.1, params=model.parameters())
# Adam optimizer
optimizer = torch.optim.Adam(lr=0.001, params=model.parameters())

```

## Save & Load Entire Model

```python
torch.save(model, 'model.pth')
model = torch.load('model.pth')
model.eval()  # Set the model to evaluation mode
```
## Save & Load Only the Model State Dict:
```python
torch.save(model.state_dict(), 'model_state_dict.pth')
model = EnhancedRNN(...)  # Initialize the model architecture
model.load_state_dict(torch.load('model_state_dict.pth'))
model.eval()  # Set the model to evaluation mode
```

# PTQ - Post training Quantization for Basic Pytorch


```python
quantized_model = torch.quantization.quantize_dynamic(
    model, {nn.RNN,nn.Linear}, dtype=torch.qint8
)


EnhancedRNN(
  (embedding): Embedding(30522, 128)
  (rnn): RNN(128, 256, num_layers=2, batch_first=True, dropout=0.5, bidirectional=True)
  (attention): MultiheadAttention(
    (out_proj): NonDynamicallyQuantizableLinear(in_features=512, out_features=512, bias=True)
  )
  (layer_norm1): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
  (layer_norm2): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
  (fc1): DynamicQuantizedLinear(in_features=512, out_features=256, dtype=torch.qint8, qscheme=torch.per_tensor_affine)
  (fc2): DynamicQuantizedLinear(in_features=256, out_features=2, dtype=torch.qint8, qscheme=torch.per_tensor_affine)
)
```


# Custom Dataset

```python

from torch.utils.data import DataLoader, Dataset

class CustomDataset(Dataset):
    def __init__(self, features, labels,...):
        # features,labels,tokenizer

    def __len__(self):
        return len(self.features)

    def __getitem__(self, idx):
        feature = self.features[idx]
        label = self.labels[idx]
        encoding = self.tokenizer(...)
        item = {key: torch.squeeze(val) for key, val in encoding.items()}
        item['labels'] = torch.tensor(label, dtype=torch.long)
        return item

dataset = CustomDataset() #<class 'list'>
dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=True)
# {'input_ids': tensor([[..],[..],..]),
#  'attention_mask': tensor([[..],[..],..]),
#  'labels': tensor([...])}

```

1. **Why do the three LSTM layers have the same dimensions?**

The three LSTM layers (`self.lstm1`, `self.lstm2`, and `self.lstm3`) have the same output dimensions (`batch_size, sequence_length, hidden_size`) because they are stacked on top of each other. In this architecture, the output of one LSTM layer is fed as input to the next LSTM layer. Since the hidden state size (`hidden_size`) remains the same across all layers, the output dimensions stay consistent.

2. **What is the significance of `num_stacked_layers`?**

The `num_stacked_layers` parameter in the LSTM layers determines the number of LSTM cells that are vertically stacked. Each LSTM cell processes the input sequence and passes its output (hidden state and cell state) to the next LSTM cell in the stack. This allows the model to learn more complex representations by capturing long-term dependencies in the input sequence.

In the provided code, `num_stacked_layers` is set to 2, which means there are two LSTM cells stacked on top of each other in each of the three LSTM layers (`self.lstm1`, `self.lstm2`, and `self.lstm3`). Increasing the number of stacked layers can potentially improve the model's performance, but it also increases the risk of overfitting and makes the model more computationally expensive.

3. **What are `h0` and `c0`?**

`h0` and `c0` are the initial hidden state and cell state, respectively, for the LSTM layers. They are required as inputs to the LSTM layers because LSTMs have a recurrent structure that depends on the previous states.

- `h0` (initial hidden state): It is a tensor of shape `(num_stacked_layers, batch_size, hidden_size)` that represents the initial hidden state of the LSTM cells. It is typically initialized with zeros.
- `c0` (initial cell state): It is a tensor of shape `(num_stacked_layers, batch_size, hidden_size)` that represents the initial cell state of the LSTM cells. It is also typically initialized with zeros.

In the provided code, `h0` and `c0` are initialized as zero tensors with the appropriate shapes and are passed to each LSTM layer during the `forward` pass:

```python
h0 = torch.zeros(self.num_stacked_layers, batch_size, self.hidden_size).to(device)
c0 = torch.zeros(self.num_stacked_layers, batch_size, self.hidden_size).to(device)

out, _ = self.lstm1(x, (h0, c0))
out, _ = self.lstm2(out, (h0, c0))
out, _ = self.lstm3(out, (h0, c0))
```

The initial hidden and cell states are used to kickstart the recurrent computation in the LSTM layers. As the input sequence is processed, the LSTM layers update the hidden and cell states based on the current input and the previous states, capturing the temporal dependencies in the sequence.


# Custom RNN model

```python


import torch
import torch.nn as nn

class EnhancedRNN(nn.Module):
    def __init__(self, ...):
        super(EnhancedRNN, self).__init__()

        # Embedding layer - (vocab_size, embed_dim)
        
        # RNN layer with multiple layers and bidirectional configuration
        # (embed_dim, hidden_dim, num_layers bidirectional=num_directions,dropout,....)

        # Multi-Headed Attention - (embed_dim * num_directions,num_heads,...)
        
        # Layer Normalization - (hidden_dim * num_directions)

        # Additional FC layers - (hidden_dim * num_directions,hidden_dim * num_directions) ,
        # (hidden_dim * num_directions,output_dim)


    def forward(self, x):
        # Embedding - [batch_size, seq_len, embed_dim]

        # RNN -  [batch_size, seq_len, hidden_dim * num_directions]
        x, _ = self.rnn(x)

        # Multi-Headed Attention
        x_attn, _ = self.attention(x, x, x)
        x = x + x_attn  # Skip connection
        x = self.layer_norm1(x)

        # Further Processing -  [batch_size, hidden_dim * num_directions]
        x = x[:, -1, :]  # Use the output from the last sequence step

        # Fully Connected layers - [batch_size, hidden_dim]
        return x


```

In [ ]:
#